---
image: docker:latest
stages:
  - build

.docker: &dind
  stage: build
  services:
  - name: docker:dind
    command: ["--mtu=1276"]
  tags:
  - dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:${ALPINE_VER} || true
    - >
      docker build 
      --platform linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
      --cache-from $CI_REGISTRY_IMAGE:${ALPINE_VER}  
      --build-arg ALPINE_VER 
      -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA-${ALPINE_VER} 
      -t $CI_REGISTRY_IMAGE:${ALPINE_VER} 
      -f Dockerfile .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA-${ALPINE_VER}
    - docker push $CI_REGISTRY_IMAGE:${ALPINE_VER}



build_edge:
  <<: *dind
  variables:
    ALPINE_VER: "edge"
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_TLS_CERTDIR: ""
