---
image: docker:latest
stages:
  - build

.docker: &dind
  stage: build
  services:
  - name: docker:dind
    command: 
    - --experimental
    - --mtu=1276
  tags:
  - dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - >
      docker build 
      --platform -platform=linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7
      -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
      -t $CI_REGISTRY_IMAGE:latest
      -f Dockerfile .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest



build_edge:
  <<: *dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_TLS_CERTDIR: ""
    DOCKER_CLI_EXPERIMENTAL: "enabled"
